# Generated by Django 2.2.5 on 2019-10-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsappnewsunit',
            table='新聞單元',
        ),
    ]
